/**
 * Schools in the Yael Foundation network (from the grant portfolio overview).
 * Seeded into the schools table; principals pick their school when they fill in their profile.
 * Only public details are kept here: name, city, country and school type.
 */
// [id, name, city, country, level]
export const SCHOOLS = [
  ["jbo-amsterdam", "JBO", "Amsterdam", "Netherlands", "k12"],
  ["mishpoche-amsterdam", "Mishpoche", "Amsterdam", "Netherlands", "supp"],
  ["kehila-ivrit-amsterdam", "Kehila Ivrit", "Amsterdam", "Netherlands", "supp"],
  ["mitsva-613-lyceum-anatevka", "Mitsva 613 Lyceum", "Anatevka", "Ukraine", "k12"],
  ["yavne-school-antwerp-antwerp", "Yavne School - Antwerp", "Antwerp", "Belgium", "k12"],
  ["tachkemoni-school-antwerp", "Tachkemoni School", "Antwerp", "Belgium", "k12"],
  ["kadima-school-auckland", "Kadima School", "Auckland", "New Zealand", "elem"],
  ["chabad-nz-auckland", "Chabad NZ", "Auckland", "New Zealand", "supp"],
  ["chabad-bad-homburg-bad-homburg", "Chabad Bad Homburg", "Bad Homburg", "Germany", "supp"],
  ["or-avner-baku-baku", "Or Avner Baku", "Baku", "Azerbaijan", "k12"],
  ["hatikva-school-barcelona", "Hatikva School", "Barcelona", "Spain", "k12"],
  ["leo-adler-basel", "Leo Adler", "Basel", "Switzerland", "supp"],
  ["chabad-serbia-belgrade", "Chabad Serbia", "Belgrade", "Serbia", "supp"],
  ["jewish-community-chabad-berlin-berlin", "Jewish Community Chabad Berlin", "Berlin", "Germany", "k12"],
  ["beit-berlin-lubavitch-berlin", "Beit Berlin Lubavitch", "Berlin", "Germany", "supp"],
  ["bila-tserkva-jewish-school-bila-tserkva", "Bila Tserkva Jewish School", "Bila Tserkva", "Ukraine", "k12"],
  ["pri-etz-haim-school-bishkek", "Pri-Etz Haim School", "Bishkek", "Kyrgyzstan", "k12"],
  ["bobruisk-jewish-community-bobruisk", "Bobruisk Jewish community", "Bobruisk", "Belarus", "supp"],
  ["gan-yossef-association-bordeaux", "Gan Yossef Association", "Bordeaux", "France", "elem"],
  ["chabad-lubawitsch-bremen-bremen", "Chabad Lubawitsch Bremen", "Bremen", "Germany", "supp"],
  ["beth-aviv-school-brussels", "Beth Aviv School", "Brussels", "Belgium", "elem"],
  ["ganenou-brussels-brussels", "Ganenou Brussels", "Brussels", "Belgium", "k12"],
  ["chabad-school-kindergarten-bucharest-buc", "Chabad School & Kindergarten Bucharest", "Bucharest", "Romania", "elem"],
  ["orach-chaim-hungary-budapest", "Orach Chaim Hungary", "Budapest", "Hungary", "supp"],
  ["maimonidesz-school-budapest", "Maimonidész School", "Budapest", "Hungary", "k12"],
  ["ilan-school-buenos-aires", "Ilan School", "Buenos Aires", "Argentina", "elem"],
  ["oholey-jinuj-school-buenos-aires", "Oholey Jinuj School", "Buenos Aires", "Argentina", "k12"],
  ["maimonides-school-buenos-aires", "Maimónides School", "Buenos Aires", "Argentina", "k12"],
  ["wolfsohn-college-buenos-aires", "Wolfsohn College", "Buenos Aires", "Argentina", "k12"],
  ["bereshit-school-buenos-aires", "Bereshit School", "Buenos Aires", "Argentina", "k12"],
  ["beth-school-ejad-buenos-aires", "Beth School Ejad", "Buenos Aires", "Argentina", "k12"],
  ["jewish-school-of-cannes-cannes", "Jewish School of Cannes", "Cannes", "France", "elem"],
  ["bukovina-jewish-center-chernivtsi", "Bukovina Jewish Center", "Chernivtsi", "Ukraine", "supp"],
  ["agudat-israel-after-school-chisinau", "Agudat Israel After School", "Chișinău", "Moldova", "supp"],
  ["the-caroline-school-copenhagen", "The Caroline School", "Copenhagen", "Denmark", "elem"],
  ["chabadenmark-copenhagen", "ChabaDenmark", "Copenhagen", "Denmark", "supp"],
  ["gan-meorot-cordoba", "Gan Meorot", "Córdoba", "Argentina", "early"],
  ["chabad-lubawitsch-sachsen-dresden", "Chabad Lubawitsch Sachsen", "Dresden", "Germany", "supp"],
  ["stratford-school-dublin", "Stratford School", "Dublin", "Ireland", "k12"],
  ["albert-einstein-gymnasium-dusseldorf", "Albert-Einstein-Gymnasium", "Düsseldorf", "Germany", "high"],
  ["moriah-school-englewood", "Moriah School", "Englewood", "United States", "k12"],
  ["jewish-community-frankfurt-frankfurt", "Jewish Community Frankfurt", "Frankfurt", "Germany", "k12"],
  ["chabad-frankfurt-frankfurt", "Chabad Frankfurt", "Frankfurt", "Germany", "supp"],
  ["jc-geneva-geneva", "JC Geneva", "Geneva", "Switzerland", "supp"],
  ["habad-geneve-geneva", "Habad Geneve", "Geneva", "Switzerland", "k12"],
  ["gibraltar-girls-high-school-gibraltar", "Gibraltar Girls High School", "Gibraltar", "Gibraltar", "k12"],
  ["beit-yakov-afterschool-gomel", "Beit Yakov Afterschool", "Gomel", "Belarus", "supp"],
  ["chabad-gothenburg-gothenburg", "Chabad Gothenburg", "Gothenburg", "Sweden", "supp"],
  ["ncjps-greater-manchester", "NCJPS", "Greater Manchester", "United Kingdom", "elem"],
  ["greenland-jewish-schools-greenland", "Greenland Jewish Schools", "Greenland", "Greenland", "k12"],
  ["chabad-hamburg-hamburg", "Chabad Hamburg", "Hamburg", "Germany", "supp"],
  ["chabad-hannover-hannover", "Chabad Hannover", "Hannover", "Germany", "supp"],
  ["jewish-school-helsinki-helsinki", "Jewish School Helsinki", "Helsinki", "Finland", "elem"],
  ["carmel-school-hong-kong", "Carmel School", "Hong Kong", "Hong Kong", "k12"],
  ["ulus-school-istanbul", "Ulus School", "Istanbul", "Turkey", "k12"],
  ["or-hajayim-school-jesus-del-monte", "Or Hajayim School", "Jesús del Monte", "Mexico", "k12"],
  ["king-david-schools-south-africa-johannes", "King David Schools South Africa", "Johannesburg", "South Africa", "k12"],
  ["beit-menachem-lyceum-kamianske", "Beit Menachem Lyceum", "Kamianske", "Ukraine", "k12"],
  ["israel-house-katowice-katowice", "Israel House - Katowice", "Katowice", "Poland", "supp"],
  ["beit-chaya-mushka-school-kiryat-arba", "Beit Chaya Mushka School", "Kiryat Arba", "Israel", "k12"],
  ["krakow-sunday-school-krakow", "Krakow Sunday School", "Krakow", "Poland", "supp"],
  ["simcha-school-kyiv", "Simcha School", "Kyiv", "Ukraine", "k12"],
  ["beyachad-jewish-center-kyiv", "BeYachad Jewish Center", "Kyiv", "Ukraine", "supp"],
  ["or-menachem-cheder-kyiv", "Or Menachem Cheder", "Kyiv", "Ukraine", "elem"],
  ["larnaca-jewish-kindergarten-school-larna", "Larnaca Jewish Kindergarten & School", "Larnaca", "Cyprus", "elem"],
  ["cilv-lausanne-lausanne", "CILV Lausanne", "Lausanne", "Switzerland", "supp"],
  ["leeds-jewish-free-school-leeds", "Leeds Jewish Free School", "Leeds", "United Kingdom", "k12"],
  ["leon-pinelo-school-lima", "Leon Pinelo School", "Lima", "Peru", "k12"],
  ["chabad-portugal-lisbon", "Chabad Portugal", "Lisbon", "Portugal", "early"],
  ["luzern-chabad-sunday-school-luzern", "Luzern Chabad Sunday School", "Luzern", "Switzerland", "supp"],
  ["ibn-gabirol-school-madrid", "Ibn Gabirol School", "Madrid", "Spain", "k12"],
  ["king-david-manchester-manchester", "King David Manchester", "Manchester", "United Kingdom", "high"],
  ["yavne-school-marseille-marseille", "Yavne School - Marseille", "Marseille", "France", "k12"],
  ["gan-ami-school-marseille", "Gan Ami School", "Marseille", "France", "k12"],
  ["comunidad-israelita-de-melilla-melilla", "Comunidad Israelita de Melilla", "Melilla", "Spain", "elem"],
  ["yavne-school-mexico-mexico-city", "Yavne School - Mexico", "Mexico City", "Mexico", "k12"],
  ["turkish-friends-of-chabad-miami-beach", "Turkish Friends of Chabad", "Miami Beach", "Turkey", "supp"],
  ["merkos-school-milan", "Merkos School", "Milan", "Italy", "k12"],
  ["or-avner-minsk-after-school-minsk", "Or Avner - Minsk After School", "Minsk", "Belarus", "supp"],
  ["integral-school-montevideo", "Integral School", "Montevideo", "Uruguay", "k12"],
  ["yavne-school-uruguay-montevideo", "Yavne School - Uruguay", "Montevideo", "Uruguay", "elem"],
  ["etz-chaim-school-moscow", "Etz Chaim School", "Moscow", "Russia", "k12"],
  ["munich-bavaria-munich", "Munich Bavaria", "Munich", "Germany", "elem"],
  ["private-lyceum-or-menachem-mykolaiv", "Private Lyceum «Or Menachem»", "Mykolaiv", "Ukraine", "elem"],
  ["abravanel-institutions-neuilly", "Abravanel Institutions", "Neuilly", "France", "elem"],
  ["marianne-picard-school-neuilly-sur-seine", "Marianne Picard School", "Neuilly sur Seine", "France", "elem"],
  ["or-torah-school-nice", "Or Torah School", "Nice", "France", "k12"],
  ["kerem-menachem-school-nice", "Kerem Menachem School", "Nice", "France", "elem"],
  ["olami-nice-nice", "Olami Nice", "Nice", "France", "supp"],
  ["or-avner-nizhny-novgorod-nizhny-novgorod", "Or Avner - Nizhny Novgorod", "Nizhny Novgorod", "Russia", "k12"],
  ["or-avner-lev-novosibirsk-novosibirsk", "Or Avner & LEV Novosibirsk", "Novosibirsk", "Russia", "k12"],
  ["chabad-nuremberg-nuremberg", "Chabad Nuremberg", "Nuremberg", "Germany", "supp"],
  ["tikva-children-s-house-odesa", "Tikva Children's House", "Odesa", "Ukraine", "k12"],
  ["chabad-or-avner-lyceum-odesa", "Chabad Or Avner Lyceum", "Odesa", "Ukraine", "k12"],
  ["oslo-jewish-community-oslo", "Oslo - Jewish Community", "Oslo", "Norway", "supp"],
  ["jcp-kindergarten-paphos", "JCP Kindergarten", "Paphos", "Cyprus", "early"],
  ["ganenou-france-paris", "Ganenou France", "Paris", "France", "elem"],
  ["ejm-paris", "EJM", "Paris", "France", "elem"],
  ["les-institutions-sinai-paris", "Les Institutions Sinai", "Paris", "France", "early"],
  ["chneor-school-paris", "Chneor School", "Paris", "France", "k12"],
  ["choosing-jewish-school-paris", "Choosing Jewish School", "Paris", "France", "other"],
  ["beth-aaron-school-paris", "Beth Aaron School", "Paris", "France", "high"],
  ["alef-beth-chaoul-school-paris", "Alef Beth Chaoul School", "Paris", "France", "elem"],
  ["alliance-israelite-universelle-paris", "Alliance Israélite Universelle", "Paris", "France", "k12"],
  ["beis-aharon-school-pinsk", "Beis Aharon School", "Pinsk", "Belarus", "k12"],
  ["beth-habad-canton-vert-plan-de-cuques", "Beth Habad Canton Vert", "Plan de Cuques", "France", "supp"],
  ["geula-kids-jewish-school-playa-del-carme", "Geula Kids Jewish School", "Playa del Carmen", "Mexico", "k12"],
  ["israel-house-prague-jcc-prague", "Israel House - Prague JCC", "Prague", "Czech Republic", "supp"],
  ["chabad-of-iceland-reykjavik", "Chabad of Iceland", "Reykjavík", "Iceland", "supp"],
  ["bait-kids-zone-richmond", "Bait Kids Zone", "Richmond", "Canada", "supp"],
  ["riga-chabad-jewish-private-school-riga", "Riga Chabad Jewish Private School", "Riga", "Latvia", "k12"],
  ["riga-jewish-community-riga", "Riga Jewish Community", "Riga", "Latvia", "early"],
  ["dubnov-afterschool-program-riga", "Dubnov Afterschool program", "Riga", "Latvia", "supp"],
  ["chai-school-international-rio-de-janeiro", "Chai School International", "Rio de Janeiro", "Brazil", "elem"],
  ["beit-chaya-muska-school-rio-de-janeiro", "Beit Chaya Muska School", "Rio de Janeiro", "Brazil", "k12"],
  ["tth-barilan-school-rio-de-janeiro", "TTH Barilan School", "Rio de Janeiro", "Brazil", "k12"],
  ["cultural-beneficial-association-rio-de-j", "Cultural Beneficial Association", "Rio de Janeiro", "Brazil", "supp"],
  ["maor-sunday-school-saint-petersburg", "Maor Sunday school", "Saint Petersburg", "Russia", "supp"],
  ["fundacion-educacional-maimonides-santiag", "Fundación Educacional Maimonides", "Santiago", "Chile", "k12"],
  ["lubavitch-gani-schools-sao-paulo", "Lubavitch Gani Schools", "São Paulo", "Brazil", "k12"],
  ["beit-chabad-morumbi-sao-paulo", "Beit Chabad Morumbi", "São Paulo", "Brazil", "supp"],
  ["smmis-singapore", "SMMIS", "Singapore", "Singapore", "k12"],
  ["chabad-of-malta-sliema", "Chabad of Malta", "Sliema", "Malta", "supp"],
  ["lauder-school-sofia-sofia", "Lauder School Sofia", "Sofia", "Bulgaria", "k12"],
  ["chabad-of-st-maur-st-maur", "Chabad of St Maur", "St Maur", "France", "supp"],
  ["jrlc-sunday-school-staten-island", "JRLC Sunday School", "Staten Island", "United States", "supp"],
  ["chabad-eftis-afterschool-stockholm", "Chabad Eftis Afterschool", "Stockholm", "Sweden", "supp"],
  ["tachbar-school-strasbourg", "Tachbar School", "Strasbourg", "France", "elem"],
  ["pardess-chaya-suresnes", "Pardess Chaya", "Suresnes", "France", "k12"],
  ["bje-sydney", "BJE", "Sydney", "Australia", "supp"],
  ["jewish-education-center-tallinn", "Jewish Education Center", "Tallinn", "Estonia", "supp"],
  ["or-avner-school-tbilisi", "Or Avner School", "Tbilisi", "Georgia", "k12"],
  ["ohr-torah-school-toulouse", "Ohr Torah School", "Toulouse", "France", "high"],
  ["tucuman-school-tucuman", "Tucuman School", "Tucuman", "Argentina", "k12"],
  ["lauder-school-vienna", "Lauder School", "Vienna", "Austria", "k12"],
  ["jrcv-center-vienna", "JRCV Center", "Vienna", "Austria", "supp"],
  ["bibi-sarah-kindergarten-vienna", "Bibi Sarah kindergarten", "Vienna", "Austria", "early"],
  ["sephardic-community-vienna", "Sephardic Community", "Vienna", "Austria", "supp"],
  ["ecole-beth-menahem-villeurbanne", "École Beth Menahem", "Villeurbanne", "France", "k12"],
  ["chai-sunday-school-warsaw", "Chai Sunday School", "Warsaw", "Poland", "supp"],
  ["jewish-organization-menorah-zagreb", "Jewish Organization Menorah", "Zagreb", "Croatia", "elem"],
  ["chabad-lubavitch-zaporizhia-zaporizhzhia", "Chabad Lubavitch Zaporizhia", "Zaporizhzhia", "Ukraine", "k12"],
  ["or-avner-gymnasium-zhytomyr", "Or Avner Gymnasium", "Zhytomyr", "Ukraine", "k12"],
  ["noam-school-zurich", "Noam School", "Zurich", "Switzerland", "elem"],
  ["chai-preschool-zurich", "Chai Preschool", "Zurich", "Switzerland", "supp"],
];
